name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          pre-commit: scripts/ci-pre-commit.js
          github-token: ${{ secrets.github_token }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Build
        run: |
          npm install
          npm run build

      - name: Publish
        uses: JS-DevTools/npm-publish@v3
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}
