name: Release

on:
  push:

permissions:
  contents: write

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
